site_name: Geo KPE Multidoc
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
# - literate-nav:
#     nav_file: SUMMARY.md
# - section-index
- mkdocstrings
# nav:
# # rest of the navigation...
# # defer to gen-files + literate-nav
# - Code Reference: reference/  # 
# # rest of the navigation...