from os import environ

MAPBOX_TOKEN = environ['MAPBOX_TOKEN']
GEO_KPE_MULTIDOC_DATA_PATH = environ['GEO_KPE_MULTIDOC_DATA_PATH']
GEO_KPE_MULTIDOC_MODELS_PATH = environ['GEO_KPE_MULTIDOC_MODELS_PATH']
GEO_KPE_MULTIDOC_OUTPUT_PATH = environ['GEO_KPE_MULTIDOC_OUTPUT_PATH']
GEO_KPE_MULTIDOC_MORDECAI_ES_URL = environ['GEO_KPE_MULTIDOC_MORDECAI_ES_URL'] 