from os import environ

GEO_KPE_MULTIDOC_MAPBOX_TOKEN = environ["GEO_KPE_MULTIDOC_MAPBOX_TOKEN"]
GEO_KPE_MULTIDOC_DATA_PATH = environ["GEO_KPE_MULTIDOC_DATA_PATH"]
GEO_KPE_MULTIDOC_MODELS_PATH = environ["GEO_KPE_MULTIDOC_MODELS_PATH"]
GEO_KPE_MULTIDOC_OUTPUT_PATH = environ["GEO_KPE_MULTIDOC_OUTPUT_PATH"]
GEO_KPE_MULTIDOC_CACHE_PATH = environ["GEO_KPE_MULTIDOC_CACHE_PATH"]
GEO_KPE_MULTIDOC_DEBUG = (
    environ.get("GEO_KPE_MULTIDOC_DEBUG", "False").lower() == "true"
)
GEO_KPE_MULTIDOC_MORDECAI_ES_URL = environ["GEO_KPE_MULTIDOC_MORDECAI_ES_URL"]
