from os import environ

MAPBOX_KEY = environ['MAPBOX_KEY']
GEO_KPE_MULTIDOC_RAWDATA_PATH = environ['GEO_KPE_MULTIDOC_RAWDATA_PATH']
GEO_KPE_MULTIDOC_OUTPUT_PATH = environ['GEO_KPE_MULTIDOC_OUTPUT_PATH']
GEO_KPE_MULTIDOC_MORDECAI_ES_URL = environ['GEO_KPE_MULTIDOC_MORDECAI_ES_URL'] 